name: Build libvconsole

on:
  push:
    branches: [ main ]
    paths:
      - 'libvconsole/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'libvconsole/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: Build libvconsole
        run: |
          cd libvconsole
          msbuild libvconsole.vcxproj /p:Configuration=Release /p:Platform=x64

      - name: Upload libvconsole artifact
        uses: actions/upload-artifact@v2
        with:
          name: libvconsole
          path: |
            libvconsole/x64/Release/libvconsole.lib
            libvconsole/src/*.h