name: Build libvconsole and CS2RemoteConsole-client

on:
  push:
    branches: [ main ]
    paths:
      - 'libvconsole/**'
      - 'CS2RemoteConsole-client/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'libvconsole/**'
      - 'CS2RemoteConsole-client/**'
  workflow_dispatch:

jobs:
  build-libvconsole:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: Build libvconsole
        run: |
          cd libvconsole
          msbuild libvconsole.vcxproj /p:Configuration=Release /p:Platform=x64

      - name: Upload libvconsole artifact
        uses: actions/upload-artifact@v2
        with:
          name: libvconsole-build
          path: |
            libvconsole/x64/Release/libvconsole.lib
            libvconsole/src/*.h

  build-cs2remoteconsole-client:
    needs: build-libvconsole
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: Download libvconsole artifact
        uses: actions/download-artifact@v2
        with:
          name: libvconsole-build
          path: libvconsole-build

      - name: Display structure of downloaded files
        run: dir /s libvconsole-build
        shell: cmd

      - name: Prepare libvconsole for CS2RemoteConsole-client
        run: |
          mkdir -p CS2RemoteConsole-client\lib
          mkdir -p CS2RemoteConsole-client\include\libvconsole
          copy libvconsole-build\libvconsole.lib CS2RemoteConsole-client\lib\
          copy libvconsole-build\src\*.h CS2RemoteConsole-client\include\libvconsole\
        shell: cmd

      - name: Build CS2RemoteConsole-client
        run: |
          cd CS2RemoteConsole-client
          msbuild CS2RemoteConsole-client.vcxproj /p:Configuration=Release /p:Platform=x64

      - name: Upload CS2RemoteConsole-client artifact
        uses: actions/upload-artifact@v2
        with:
          name: CS2RemoteConsole-client-build
          path: CS2RemoteConsole-client/x64/Release/CS2RemoteConsole-client.exe