name: Build CS2RemoteConsole-server

on:
  push:
    branches: [ master ]
    paths:
      - 'CS2RemoteConsole-server/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'CS2RemoteConsole-server/**'
  workflow_dispatch:

jobs:
  build-cs2remoteconsole-server:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: Build CS2RemoteConsole-server
        run: |
          cd CS2RemoteConsole-server
          msbuild CS2RemoteConsole-server.vcxproj /p:Configuration=Release /p:Platform=x64

      - name: Prepare artifact directory
        run: |
          mkdir artifact
          copy "CS2RemoteConsole-server\x64\Release\CS2RemoteConsole-server.exe" "artifact\"
        shell: cmd

      - name: Verify artifact contents
        run: |
          echo "Verifying artifact contents:"
          dir artifact
        shell: cmd

      - name: Upload CS2RemoteConsole-server artifact
        uses: actions/upload-artifact@v2
        with:
          name: CS2RemoteConsole-server-build
          path: artifact